# Generated by Django 4.2.2 on 2023-07-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(max_length=100)),
                ('countrypopulation', models.IntegerField()),
                ('countryimage', models.ImageField(upload_to=None)),
                ('countrybreadth', models.IntegerField()),
                ('countrywonder', models.IntegerField()),
                ('Descripition', models.CharField(max_length=100)),
            ],
        ),
    ]
