# Generated by Django 4.2.2 on 2023-07-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_country_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Descripition',
            field=models.CharField(max_length=250),
        ),
    ]
