# Generated by Django 4.2.2 on 2023-07-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_country_descripition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='countrybreadth',
            new_name='countrywonders',
        ),
        migrations.RemoveField(
            model_name='country',
            name='countrypopulation',
        ),
        migrations.RemoveField(
            model_name='country',
            name='countrywonder',
        ),
        migrations.AddField(
            model_name='country',
            name='countryfood',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='countrylanguage',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
